### PR TITLE
do_lint: Add option to print custom message on failure.

### PR DESCRIPTION
**Pull request by amanagr**
This could be used to guide users to fix the errors.

### CODE REVIEW

**Comment by andersk** [comment]
`message_on_error` is a bit of a weird interface. You [mentioned](https://chat.zulip.org/#narrow/stream/49-development-help/topic/first.20issue/near/1033711) that the use case is `Run ./tools/lint --fix to auto fix some of the errors`, but we can get all we need to construct that message from `sys.argv[0]`. Also, it might be nice to check whether any of the linters that failed even have `check_arg` or `fix_arg`.

**Comment by amanagr** [comment]
@andersk updated! Thanks for the pointers.

**Comment by amanagr** [comment]
@andersk ping.

**Comment by andersk** [comment]
Merged with minor changes (see commit message or [diff](https://github.com/zulip/zulint/compare/5f47f626fc2c434fb914b4de56411c2e7cb8d330..e8c7e42440e8b1a2e58316e16437e815cacfd495)).

**Comment by amanagr** [comment]
Thanks, I will open PRs in other repos to update this.

**Pull request merged**
